spring:
  application:
    name: trading-app

  datasource:
    url: jdbc:mysql://localhost:3306/dhandb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path:

broker:
  configs:
    broker-name: aliceblue
    app-key: ${ALICEBLUE_APP_KEY}
    user-id: ${ALICEBLUE_USER_ID}
    app-secret: ${ALICEBLUE_APP_SECRET}
    redirect-url: http://localhost:8080/callback
    auth-url: https://ant.aliceblueonline.com
    base-url: https://a3.aliceblueonline.com

jwt:
  secret: io/lFrD2JmpTG7Wzj7ELBuVVCC+RRBaCEPo43fY7gmc=
  expiration: 86400000