server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trading
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


    base_url : "https://a3.aliceblueonline.com"